# Generated by Django 5.1.1 on 2024-09-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='first_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(1, 'مرد'), (2, 'زن')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='last_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
