# Generated by Django 5.1.1 on 2024-09-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_sellerprofile_first_name_sellerprofile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'مرد'), (2, 'زن')], null=True),
        ),
    ]
