# Generated by Django 5.1.1 on 2024-09-23 16:17

import jalali_date_new.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=jalali_date_new.model_fields.JalaliDateTimeModelField(),
        ),
    ]
