# Generated by Django 5.1.1 on 2024-09-22 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_customerprofile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='phone_number',
        ),
    ]
