# Generated by Django 5.1.1 on 2024-09-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_customerprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'مرد'), (2, 'زن')], null=True),
        ),
    ]
