# Generated by Django 5.1.1 on 2024-09-22 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_address'),
        ('vendors', '0003_category_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.sellerprofile'),
            preserve_default=False,
        ),
    ]
