# Generated by Django 5.1.1 on 2024-09-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_discount_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('fixed', 'ثابت'), ('percentage', 'درصدی')], max_length=50),
        ),
    ]
