# Generated by Django 5.1.1 on 2024-09-23 16:17

import jalali_date_new.model_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_product_sales_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=jalali_date_new.model_fields.JalaliDateTimeModelField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=jalali_date_new.model_fields.JalaliDateTimeModelField(),
        ),
    ]
