# Generated by Django 5.1.1 on 2024-09-23 16:33

import jalali_date_new.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_alter_discount_value_alter_product_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=jalali_date_new.model_fields.JalaliDateTimeModelField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=jalali_date_new.model_fields.JalaliDateTimeModelField(auto_now=True),
        ),
    ]
