# Generated by Django 5.1.1 on 2024-09-23 16:17

import jalali_date_new.model_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_updated_at_cartitem_price_order_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=jalali_date_new.model_fields.JalaliDateTimeModelField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='updated_at',
            field=jalali_date_new.model_fields.JalaliDateTimeModelField(),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=jalali_date_new.model_fields.JalaliDateTimeModelField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=jalali_date_new.model_fields.JalaliDateTimeModelField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.IntegerField(),
        ),
    ]
